# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install required system dependencies
RUN apt-get update && \
    apt-get install -y build-essential default-libmysqlclient-dev python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and install Python dependencies
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt \
    pip install mysql-connector-python pandas


# Set the environment variables
ENV MYSQL_HOST=host.docker.internal \
    MYSQL_PORT=3306 \
    MYSQL_ROOT_USER=senrayan \
    MYSQL_ROOT_PASSWORD=Pa$$w0rd


# Expose the port your Flask app will run on
EXPOSE 8888

# Run the application using Gunicorn
CMD ["gunicorn", "-b", "0.0.0.0:8888", "app:app"]
