"""Initial migration

Revision ID: e83367e17e8b
Revises: 
Create Date: 2024-01-17 22:41:38.911448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e83367e17e8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=False),
    sa.Column('ph_no', sa.String(length=15), nullable=False),
    sa.Column('msg', sa.String(length=500), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('posts',
    sa.Column('sno', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=25), nullable=False),
    sa.Column('subtitle', sa.String(length=90), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('img_file', sa.String(length=40), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
