apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-blog-app
  template:
    metadata:
      labels:
        app: my-blog-app
    spec:
      containers:
      - name: blog-container
        image: your-blog-image:latest
        ports:
        - containerPort: 80
