name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh -v 3.12.3

      - name: Package Helm Chart
        run: |
          helm package ./k8s/blog -d ./k8s
          mv ./k8s/blog-*.tgz ./k8s/blog-0.1.0.tgz

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Helm
        run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod +x get_helm.sh
          ./get_helm.sh -v 3.12.3

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install blog ./k8s/blog-0.1.0.tgz
